version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["/", "/.github/actions/setup-ghtools"]
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
