"""Keep other repositories' workflow stubs current, one pull request each."""

from __future__ import annotations

import base64
import json
import re
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import scaffold
from .ci import STUB_PATH
from .errors import GhtoolsError

_MARKER = re.compile(r"# ghtools-stub: (\d+)")
_PIN = re.compile(r"pipeline\.yml@(\S+)")


def stub_version(text: str) -> int:
    m = _MARKER.search(text)
    return int(m.group(1)) if m else 0


def stub_ref(text: str) -> str:
    m = _PIN.search(text)
    return m.group(1) if m else scaffold.STUB_REF


def restub(root: Path) -> str | None:
    """The repo's stub re-rendered for the current contract, or None if it is already current."""
    text = (Path(root) / STUB_PATH).read_text(encoding="utf-8")
    if stub_version(text) >= scaffold.STUB_VERSION:
        return None
    return scaffold.current_stub(Path(root))  # keeps the pin; settings from the repo's own toml


Gh = Callable[[list[str]], Any]


@dataclass
class Outcome:
    repo: str
    state: str
    detail: str = ""


def remote_stub(repo: str, gh: Gh) -> str | None:
    data = gh(["api", f"repos/{repo}/contents/{STUB_PATH}"])
    if not data or "content" not in data:
        return None
    return base64.b64decode(data["content"]).decode("utf-8")


def discover(owner: str, gh: Gh) -> list[str]:
    repos = (
        gh(["repo", "list", owner, "--limit", "300", "--json", "nameWithOwner,isArchived,isFork"])
        or []
    )
    live = [r["nameWithOwner"] for r in repos if not r["isArchived"] and not r["isFork"]]
    return [r for r in live if remote_stub(r, gh) is not None]


def gh_clone(repo: str, dest: Path) -> None:
    subprocess.run(["gh", "repo", "clone", repo, str(dest), "--", "--depth", "1", "-q"], check=True)


def run_git(args: list[str], cwd: Path) -> str:
    # gh's credential helper, so private repos push without a token on the command line.
    helper = ["-c", "credential.helper=", "-c", "credential.helper=!gh auth git-credential"]
    proc = subprocess.run(["git", *helper, *args], cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise GhtoolsError(f"git {' '.join(args)}: {proc.stderr.strip()}")
    return proc.stdout


def _pr_body(old: int) -> str:
    changes = "\n".join(
        f"- v{n}: {scaffold.STUB_CHANGES[n]}" for n in range(old + 1, scaffold.STUB_VERSION + 1)
    )
    return (
        "Updates `.github/workflows/ghtools.yml` from stub contract "
        f"v{old} to v{scaffold.STUB_VERSION}.\n\n"
        f"{changes}\n\n"
        "The stub was re-rendered from this repository's own `.github/ghtools.toml`, keeping "
        "its pinned ref. Nothing else changed. Generated by `ghtools sync`."
    )


def sync_repo(
    repo: str,
    *,
    gh: Gh,
    clone: Callable[[str, Path], None] | None,
    run_git: Callable[[list[str], Path], str] | None,
    dry_run: bool,
) -> Outcome:
    try:
        return _sync_repo(repo, gh=gh, clone=clone, run_git=run_git, dry_run=dry_run)
    except (GhtoolsError, subprocess.CalledProcessError) as exc:
        # One repo's failure (API error, clone, push) never stops the others.
        detail = getattr(exc, "stderr", None) or str(exc)
        return Outcome(repo, "failed", str(detail).strip())


def _sync_repo(
    repo: str,
    *,
    gh: Gh,
    clone: Callable[[str, Path], None] | None,
    run_git: Callable[[list[str], Path], str] | None,
    dry_run: bool,
) -> Outcome:
    text = remote_stub(repo, gh)
    if text is None:
        return Outcome(repo, "not-set-up")
    old = stub_version(text)
    if old >= scaffold.STUB_VERSION:
        return Outcome(repo, "up-to-date", f"v{old}")
    branch = f"ghtools/stub-v{scaffold.STUB_VERSION}"
    open_prs = (
        gh(["pr", "list", "--repo", repo, "--head", branch, "--state", "open", "--json", "number"])
        or []
    )
    if open_prs:
        return Outcome(repo, "already-proposed", f"PR #{open_prs[0]['number']}")
    if dry_run:
        return Outcome(repo, "would-propose", f"v{old} -> v{scaffold.STUB_VERSION}")
    assert clone is not None and run_git is not None
    with tempfile.TemporaryDirectory(prefix="ghtools-sync-") as tmp:
        work = Path(tmp) / "repo"
        try:
            clone(repo, work)
        except subprocess.CalledProcessError as exc:
            return Outcome(repo, "failed", f"clone failed: {(exc.stderr or exc).__str__().strip()}")
        try:
            new = restub(work)
        except GhtoolsError as exc:
            return Outcome(repo, "failed", str(exc))
        if new is None:
            return Outcome(repo, "up-to-date", "default branch already current")
        (work / STUB_PATH).write_text(new, encoding="utf-8")
        title = f"ci(ghtools): update the workflow stub to contract v{scaffold.STUB_VERSION}"
        try:
            run_git(["switch", "-q", "-c", branch], work)
            run_git(["commit", "-q", "-am", title], work)
            # ghtools owns this branch; one left by a closed PR or a failed `gh pr create` is
            # simply replaced (a branch with an open PR was skipped above).
            run_git(["push", "-q", "--force", "origin", branch], work)
        except (GhtoolsError, subprocess.CalledProcessError) as exc:
            return Outcome(repo, "failed", str(exc))
        pr = gh(
            [
                "pr",
                "create",
                "--repo",
                repo,
                "--head",
                branch,
                "--title",
                title,
                "--body",
                _pr_body(old),
            ]
        )
    if not pr or "url" not in pr:
        reason = (pr or {}).get("error", "no output")
        return Outcome(repo, "failed", f"pushed {branch} but gh pr create failed: {reason}")
    return Outcome(repo, "proposed", pr["url"])


def real_gh(args: list[str]) -> Any:
    """Run gh: parsed JSON, None for an HTTP 404, and a GhtoolsError for any other failure."""
    proc = subprocess.run(["gh", *args], capture_output=True, text=True)
    if args[:2] == ["pr", "create"]:  # prints the URL, not JSON
        if proc.returncode == 0:
            return {"url": proc.stdout.strip()}
        return {"error": proc.stderr.strip()}
    if proc.returncode != 0:
        if "HTTP 404" in proc.stderr:
            return None
        raise GhtoolsError(f"gh {' '.join(args[:2])}: {proc.stderr.strip()}")
    return json.loads(proc.stdout) if proc.stdout.strip() else None
