from __future__ import annotations

import json

from ghtools import config
from ghtools.status.render import render_all


def test_render_all_produces_data_card_badges_and_readme(tmp_path):
    data = {
        "project": {"name": "x", "description": "d", "version": "1.0.0", "links": {}},
        "ci": {"tests": {"passed": 1, "failed": 0, "skipped": 0, "total": 1}, "coverage": 90.0},
    }
    cfg = config.from_dict({"status": {"enabled": True}})
    files = render_all(data, cfg, tmp_path)
    assert set(files) >= {
        "data/project.json",
        "data/ci.json",
        "status.svg",
        "badges/version.svg",
        "badges/coverage.svg",
        "badges/tests.svg",
        "README.md",
    }
    assert json.loads(files["data/ci.json"])["coverage"] == 90.0
    assert files["status.svg"].startswith(b"<svg")
    assert b"generated by ghtools" in files["README.md"]
