"""Tests for ghtools.codecov: .github/codecov.yml rendered from .github/ghtools.toml."""

from __future__ import annotations

import pytest
import yaml

from ghtools import codecov, config
from ghtools.cli import main
from ghtools.errors import ConfigError


def _load(cfg_dict):
    return yaml.safe_load(codecov.render(config.from_dict(cfg_dict)))


def test_default_policy_allows_a_two_percent_drop_and_never_fails_on_patch():
    doc = _load({})
    assert doc["coverage"]["status"]["project"]["default"] == {"target": "auto", "threshold": "2%"}
    assert doc["coverage"]["status"]["patch"]["default"]["informational"] is True
    assert "component_management" not in doc
    assert {"tests/**", "docs/**"} <= set(doc["ignore"])


def test_threshold_and_components_come_from_the_toml():
    doc = _load(
        {
            "ci": {
                "coverage": {
                    "threshold": 1.5,
                    "component": [
                        {"id": "db", "name": "database", "paths": ["src/x/db/**"]},
                        {"id": "cli", "name": "CLI", "paths": ["src/x/cli.py"]},
                    ],
                }
            }
        }
    )
    assert doc["coverage"]["status"]["project"]["default"]["threshold"] == "1.5%"
    cm = doc["component_management"]
    assert cm["default_rules"]["statuses"] == [
        {"type": "project", "target": "auto", "threshold": "1.5%"}
    ]
    assert cm["individual_components"][0] == {
        "component_id": "db",
        "name": "database",
        "paths": ["src/x/db/**"],
    }
    assert "components" in doc["comment"]["layout"]


@pytest.mark.parametrize(
    "row",
    [
        {"id": "db", "name": "database", "paths": []},
        {"id": "Bad Id", "name": "x", "paths": ["a"]},
    ],
)
def test_components_are_validated(row):
    with pytest.raises(ConfigError):
        config.from_dict({"ci": {"coverage": {"component": [row]}}})


def test_negative_threshold_is_rejected():
    with pytest.raises(ConfigError):
        config.from_dict({"ci": {"coverage": {"threshold": -1}}})


def test_cli_check_write_and_opt_out(git_repo):
    git_repo.commit("feat: a", {".github/ghtools.toml": ""})
    args = ["-C", str(git_repo.path), "codecov"]
    assert main([*args, "--check"]) != 0  # missing file is drift
    assert main([*args, "--write"]) == 0
    written = git_repo.path / ".github/codecov.yml"
    assert written.read_text().startswith("# Generated by ghtools")
    assert main([*args, "--check"]) == 0
    written.write_text(written.read_text().replace("2%", "0%"))
    assert main([*args, "--check"]) != 0
    (git_repo.path / ".github/ghtools.toml").write_text("[ci.coverage]\ncodecov = false\n")
    assert main([*args, "--check"]) == 0  # Codecov off: nothing to keep in step


def test_check_fails_while_another_codecov_file_takes_precedence(git_repo):
    git_repo.commit("feat: a", {".github/ghtools.toml": "", "codecov.yml": "coverage: {}\n"})
    args = ["-C", str(git_repo.path), "codecov"]
    assert main([*args, "--write"]) == 0
    assert main([*args, "--check"]) != 0  # the root codecov.yml would shadow ours
    (git_repo.path / "codecov.yml").unlink()
    assert main([*args, "--check"]) == 0


def test_codecov_sync_gate_is_builtin():
    from ghtools.gates import BUILTIN

    assert BUILTIN["codecov-sync"].run == "ghtools codecov --check"
    config.from_dict({"ci": {"gates": ["codecov-sync"]}})  # accepted


PREFIX = "ghtools-codecov-root-2026-10-09-"


@pytest.mark.parametrize(
    ("matched", "limit", "want"),
    [
        ("", 1, (True, PREFIX + "1")),  # first upload today
        (PREFIX + "1", 1, (False, "")),  # the default: one a day
        (PREFIX + "1", 3, (True, PREFIX + "2")),
        (PREFIX + "3", 3, (False, "")),
        (PREFIX + "12", 20, (True, PREFIX + "13")),
        ("ghtools-codecov-root-2026-10-08-1", 1, (True, PREFIX + "1")),  # yesterday's
        (PREFIX + "x", 1, (True, PREFIX + "1")),  # not a count: no upload recorded
        (PREFIX + "5", 0, (True, "")),  # no limit: upload, record nothing
    ],
)
def test_quota_counts_todays_uploads_from_the_newest_key(matched, limit, want):
    assert codecov.quota(PREFIX, matched, limit) == want


def test_uploads_per_day_defaults_to_one_and_rejects_negatives():
    assert config.from_dict({}).get("ci.coverage.uploads-per-day") == 1
    with pytest.raises(ConfigError):
        config.from_dict({"ci": {"coverage": {"uploads-per-day": -1}}})


def test_cli_quota_writes_outputs_and_explains_a_skip(git_repo, tmp_path, monkeypatch, capsys):
    git_repo.commit("feat: a", {".github/ghtools.toml": ""})
    out = tmp_path / "github_output"
    monkeypatch.setenv("GITHUB_OUTPUT", str(out))
    args = ["-C", str(git_repo.path), "ci", "codecov-quota", "--prefix", PREFIX]
    assert main([*args, "--github-output"]) == 0
    assert out.read_text() == f"upload=true\nkey={PREFIX}1\n"
    out.write_text("")
    assert main([*args, "--matched", PREFIX + "1", "--github-output"]) == 0
    assert out.read_text() == "upload=false\nkey=\n"
    assert "::notice title=Codecov upload skipped::" in capsys.readouterr().out
