"""All files published on the status branch, rendered from the merged fragments."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..config import Config
from .badges import badges_for
from .model import render_card

BRANCH_README = """# ghtools status branch

Everything on this branch is generated by ghtools (https://github.com/will-roscoe/.ghtools)
and replaced on every publish; each publish is a single commit with no history. Do not edit it.

- `status.svg` is the status card and `badges/*.svg` are the badges; link them from the README as
  `https://github.com/<owner>/<repo>/raw/{branch}/status.svg`.
- `data/*.json` are the per-source fragments the card is rendered from.
"""


def render_all(data: dict[str, dict[str, Any]], cfg: Config, root: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for name, fragment in sorted(data.items()):
        files[f"data/{name}.json"] = (
            json.dumps(fragment, indent=2, sort_keys=True) + "\n"
        ).encode()
    files["status.svg"] = render_card(data, cfg, root).encode()
    for path, svg in badges_for(data, cfg).items():
        files[path] = svg.encode()
    files["README.md"] = BRANCH_README.format(branch=cfg.get("status.branch")).encode()
    return files
